version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Oslo'
      # The correct native v6 password variable
      FTLCONF_webserver_api_password: ${PIHOLE_ADMIN_PASSWORD}
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
      - ./adlists.list:/etc/pihole/adlists.list:ro

volumes:
  pihole_config:
  dnsmasq_config:
