---
- name: Provision Docker VM on Proxmox
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create the Virtual Machine from Cloud-Init Template
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ lookup('ansible.builtin.env', 'PVE_PASSWORD') }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        
        cores: "{{ vm_cores }}"
        memory: "{{ vm_memory }}"
        scsihw: "{{ vm_scsi_hardware }}"
        
        netif:
          net0: "virtio,bridge={{ vm_network_bridge }}"
        
        disk:
          - size: "{{ vm_disk_size }}"
            type: "{{ vm_disk_type }}"
            storage: "{{ target_storage }}"
            import_from: "{{ vm_os_image }}"
            
        sshkeys: "{{ vm_ssh_public_key }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
          
        state: present

    - name: Start the Virtual Machine
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ lookup('ansible.builtin.env', 'PVE_PASSWORD') }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        state: started